"""PDF report generation (fpdf2).

Writing this file is the system's irreversible external action — it is gated by
the human-in-the-loop "Approve & Generate Report" button in the UI.
"""

from __future__ import annotations

import os
from typing import Optional

from fpdf import FPDF
from fpdf.enums import XPos, YPos

from state import GraphState


def _clean(text: str) -> str:
    """fpdf2's core fonts are latin-1; drop characters they can't encode."""
    return (text or "").encode("latin-1", "replace").decode("latin-1")


class _Report(FPDF):
    def _line(self, text: str, h: float = 5.5):
        """multi_cell that always uses the full effective page width and resets
        x to the left margin first (avoids fpdf2's zero-width edge case)."""
        self.set_x(self.l_margin)
        self.multi_cell(self.epw, h, _clean(text), new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    def header(self):
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(20, 50, 90)
        self._line("Startup Idea Validation Report", h=10)
        self.set_draw_color(20, 50, 90)
        self.line(self.l_margin, self.get_y(), self.w - self.r_margin, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(120, 120, 120)
        self.cell(0, 10, f"Page {self.page_no()}  -  Generated by AI Startup Mentor", align="C")

    def section(self, title: str):
        self.ln(2)
        self.set_font("Helvetica", "B", 12)
        self.set_text_color(20, 50, 90)
        self._line(title, h=7)
        self.set_text_color(0, 0, 0)
        self.set_font("Helvetica", "", 10)

    def field(self, label: str, value: str):
        self.set_font("Helvetica", "B", 10)
        self._line(f"{label}:")
        self.set_font("Helvetica", "", 10)
        self._line(value or "-")
        self.ln(1)

    def bullets(self, label: str, items):
        self.set_font("Helvetica", "B", 10)
        self._line(f"{label}:")
        self.set_font("Helvetica", "", 10)
        for it in items or ["-"]:
            self._line(f"  - {it}")
        self.ln(1)


def generate_pdf(state: GraphState, out_dir: str = "reports") -> str:
    """Render the final graph state to a PDF and return its file path."""
    os.makedirs(out_dir, exist_ok=True)

    pdf = _Report()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # --- Idea ---
    iv = state.get("idea_validation")
    pdf.section("1. Idea Validation")
    if iv:
        pdf.field("Idea", state.get("idea_summary", ""))
        pdf.field("Target customer", iv.target_customer)
        pdf.field("Problem clarity (1-5)", str(iv.problem_clarity))
        pdf.field("Pain severity (1-5)", str(iv.pain_severity))
        pdf.bullets("Demand signals", iv.demand_signals)

    # --- Market ---
    mr = state.get("market_research")
    pdf.section("2. Market & Competitor Intelligence")
    if mr:
        pdf.field("Market size", f"{mr.market_size_estimate} - {mr.market_size_rationale}")
        pdf.bullets("Growth signals", mr.growth_signals)
        pdf.bullets("Customer segments", mr.customer_segments)
        pdf.field("Direct competitors found", str(mr.competitor_count))
        for c in mr.competitors:
            pdf.bullets(
                c.name,
                [f"{c.type}, {c.funding_stage}", c.one_line_description, c.source_url],
            )
        if mr.market_notes:
            pdf.field("Notes", mr.market_notes)

    # --- Strategy ---
    st = state.get("strategy")
    pdf.section("3. Strategy")
    if st:
        pdf.field("Strategy type", st.strategy_type)
        pdf.field("Key message", st.key_message)
        pdf.field("Positioning", st.positioning)
        if st.strategy_type == "differentiation":
            pdf.field("Differentiation axis", st.differentiation_axis or "-")
            pdf.field("USP", st.usp or "-")
            pdf.field("Anti-positioning", st.anti_positioning or "-")
            pdf.field("Beachhead segment", st.beachhead_segment or "-")
            for g in st.competitor_gaps:
                pdf.field(f"Gap - {g.competitor}", g.gap)
        else:
            pdf.field("Scenario", f"{st.scenario or '-'}: {st.scenario_rationale or ''}")
            pdf.field("Category name", st.category_name or "-")
            pdf.field("Wedge use case", st.wedge_use_case or "-")

    # --- Business model ---
    bm = state.get("biz_model")
    pdf.section("4. Business Model & MVP")
    if bm:
        pdf.field("Revenue model", f"{bm.revenue_model} - {bm.revenue_model_rationale}")
        pdf.field("Pricing", f"{bm.pricing_strategy} - {bm.pricing_rationale}")
        pdf.bullets("Phase 1 features (pre-revenue)", bm.phase_1_features)
        pdf.bullets("Phase 2 features (first revenue)", bm.phase_2_features)
        pdf.bullets("Tech requirements", bm.tech_requirements)

    # --- Risk ---
    rk = state.get("risk")
    pdf.section("5. Risk Assessment")
    if rk:
        pdf.field("Overall risk score (1-10)", str(rk.overall_risk_score))
        for label, dim in [
            ("Market risk", rk.market_risk),
            ("Technical risk", rk.technical_risk),
            ("Business risk", rk.business_risk),
            ("Regulatory risk", rk.regulatory_risk),
        ]:
            pdf.field(f"{label} [{dim.risk_level}]", f"{dim.description} | Mitigation: {dim.mitigation}")
        pdf.bullets("Top 3 mitigation actions", rk.top_3_mitigation_actions)

    warning: Optional[str] = state.get("escalation_warning")
    if warning:
        pdf.section("Guardrail Notice")
        pdf.field("Human escalation", warning)

    summary = state.get("idea_summary", "report").strip().lower()
    slug = "".join(ch if ch.isalnum() else "_" for ch in summary)[:40] or "report"
    path = os.path.join(out_dir, f"validation_{slug}.pdf")
    pdf.output(path)
    return path
